#!/bin/bash -e
export PATH=/opt/rbenv/bin:/opt/rbenv/shims:${PATH}
export LANG=en_US.UTF-8
export RBENV_ROOT=/opt/rbenv


BASE_DIR=`dirname $0`

cd $BASE_DIR

rbenv version 2.0.0-p247

exec bundle exec rackup -p 4111 --pid /tmp/cronmon.pid 2>&1

